### ISSUE TITLE
Executive summary resources

### ISSUE THREAD

**Issue by Vylest** [APlusTeam/ISQA-3420#15]
Hi guys, I was looking around for guides about how to write executive summaries and found three thorough ones. They are definitely worth looking at.

http://www.inc.com/guides/2010/09/how-to-write-an-executive-summary.html

http://articles.bplans.com/writing-an-executive-summary/

http://www.wikihow.com/Write-an-Executive-Summary

**Comment by amarangonihengling** [comment]
Hi Eric, 
Please, update the wiki of the repo with these links.
Thank you!

**Comment by gasrcpro** [comment]
Closing this issue as the Executive Summary has been written.
