### ISSUE TITLE
Update DFD so the DFD is concurrent with information presented in class on 10/12/2015

### ISSUE THREAD

**Issue by gasrcpro** [APlusTeam/ISQA-3420#16]
![image](https://cloud.githubusercontent.com/assets/14644565/10436442/f86c4e90-70eb-11e5-92ba-927557cfe52c.png)

**Comment by amarangonihengling** [comment]
![dfd](https://cloud.githubusercontent.com/assets/11740062/10493517/43aba95a-7277-11e5-9876-c6a106b7df53.png)

**Comment by amarangonihengling** [comment]
DFD updated!
