### ISSUE TITLE
Update DFD

### ISSUE THREAD

**Issue by Vylest** [APlusTeam/ISQA-3420#20]
Need to add the contribution back to OS community, and vulnerability look ups, also restructure CPE info lookup

**Comment by Vylest** [comment]
![dfd_updated_110915](https://cloud.githubusercontent.com/assets/12487092/11047253/01a3bcd4-86f7-11e5-8dfc-3ce28196fda1.png)

**Comment by amarangonihengling** [comment]
Already done and updated!
