### ISSUE TITLE
Make executive summary less specific

### ISSUE THREAD

**Issue by Vylest** [APlusTeam/ISQA-3420#21]
Make that generic, yo

**Comment by gasrcpro** [comment]
The problem section of the Executive summary is fine; the solution section is what needs to be less specific.

**Comment by amarangonihengling** [comment]
What is the deadline for this issue?

**Comment by gasrcpro** [comment]
I am unsure what the deadline should be for this issue. Go ahead and set a reasonable one.

**Comment by Vylest** [comment]
I took out quite a bit of the tech jargon, using the reasoning that the people who read the executive summary probably don't care about the technical aspects.
