### ISSUE TITLE
Improve the ERD 

### ISSUE THREAD

**Issue by amarangonihengling** [APlusTeam/ISQA-3420#22]
Add field type (data type), Optional/Mandatory (null or not null), default value (if applicable), cardinality between the tables' relationship.

Make it on Visio or a nice editor.

**Comment by amarangonihengling** [comment]
What is the deadline for this issue?

**Comment by Vylest** [comment]
ERD is now updated.

![erd_1 1](https://cloud.githubusercontent.com/assets/12487092/11199324/2cac5dbe-8c92-11e5-8d33-b9da3bb3d806.png)
