### ISSUE TITLE
Create the "File" table on the ERD 

### ISSUE THREAD

**Issue by amarangonihengling** [APlusTeam/ISQA-3420#23]
Create the last table on the ERD.

**Comment by amarangonihengling** [comment]
What is the deadline for this issue?

**Comment by Vylest** [comment]
I dunno the deadline, but here is the ERD in visio
![erd_1 1](https://cloud.githubusercontent.com/assets/12487092/11199324/2cac5dbe-8c92-11e5-8d33-b9da3bb3d806.png)

**Comment by Vylest** [comment]
That diagram above is missing stuff, I forgot the foreign keys and table relationships. I fixed it in ERD 1.1

Updated ERD and closing issue.

![erd_1 1](https://cloud.githubusercontent.com/assets/12487092/11199324/2cac5dbe-8c92-11e5-8d33-b9da3bb3d806.png)
