### ISSUE TITLE
Create presentation script for the final presentation to the class

### ISSUE THREAD

**Issue by gasrcpro** [APlusTeam/ISQA-3420#29]
The presentation needs to be 15minutes long.

**Comment by gasrcpro** [comment]
No longer needed, we presented at 02:00pm on 12/07/15.

**Comment by amarangonihengling** [comment]
This is still needed. The professor talked about it today.

**Comment by gasrcpro** [comment]
Was that before I arrived? I didn't hear that. What would it be needed for? There is an issue to create the presentation, but we still need a script on what we said?

**Comment by amarangonihengling** [comment]
Yes, it was. It should be just the bullet points of the power point presentation following the format:

Slide 1: Title
* Content
* Content 
* Content

...

**Comment by gasrcpro** [comment]
Isn't that what issue #28 is for?

@amarangonihengling

**Comment by amarangonihengling** [comment]
It could be. We can close this issue now and work on issue #28 then.
We will have to change the description of issue #28 since we do not need to upload an image of the slide as a .md file.
Does it sound right to you?
