### ISSUE TITLE
Create the ERD diagram in general in Visio.

### ISSUE THREAD

**Issue by gasrcpro** [APlusTeam/ISQA-3420#31]
Up to this point the ERD diagram is only made in powerpoint, this needs to be created now in Visio.

**Comment by Vylest** [comment]
I got this, will report back when I finish it

**Comment by Vylest** [comment]
Based on the SPDX documentation, I made this ERD.
![erd_1 0](https://cloud.githubusercontent.com/assets/12487092/11199217/511a083c-8c91-11e5-93bd-109da9fbcbd2.png)
