### ISSUE TITLE
Separate data flow lines to the 'Mange Policy Process'

### ISSUE THREAD

**Issue by gasrcpro** [APlusTeam/ISQA-3420#35]

**Comment by amarangonihengling** [comment]
Follow the example

![2015-11-16 14 18 53](https://cloud.githubusercontent.com/assets/11740062/11196786/b060bc72-8c7e-11e5-9de3-b970a14662a2.jpg)

**Comment by amarangonihengling** [comment]
Done!


![dfd_updated_111615](https://cloud.githubusercontent.com/assets/11740062/11197003/1f0b20c6-8c80-11e5-9cbe-59bc64d1e737.png)
