### ISSUE TITLE
ERD Comments

### ISSUE THREAD

**Issue by germonprez** [APlusTeam/ISQA-3420#45]
A document will contain only one package -- just a logistical issue
A project can contain many packages -- you may want to add a project table 

Remove the SPDX identifiers -- These tables can work without the specific references to SPDX

**Comment by Vylest** [comment]
Oh ok, so I got the relation that wrong.  I will rename those primary keys and make a project table and sort that out. Thanks Matt.

**Comment by germonprez** [comment]
Sounds good.

matt


On Sat, Nov 21, 2015 at 1:03 AM, Eric <notifications@github.com> wrote:

> Oh ok, so I got the relation that wrong. I will rename those primary keys
> and make a project table and sort that out. Thanks Matt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/APlusTeam/ISQA-3420/issues/45#issuecomment-158598894>.
>



-- 
Mutual of Omaha Associate Professor
Information Systems
College of Information Science & Technology
University of Nebraska Omaha
http://ocrl.unomaha.edu/

**Comment by Vylest** [comment]
![erd_1 2](https://cloud.githubusercontent.com/assets/12487092/11349828/e4e2a148-91f3-11e5-9dee-316e3b6a2462.png)

Here is the updated file
