### ISSUE TITLE
Remove duplicities from the DFD Dictionary

### ISSUE THREAD

**Issue by amarangonihengling** [APlusTeam/ISQA-3420#48]
Analyze the DFD Dictionary and remove duplicities.

**Comment by gasrcpro** [comment]
@amarangonihengling, @Vylest 

Is this on track to be completed by Wednesday 12/09/15?

**Comment by gasrcpro** [comment]
Closed in error, re-opened.  Please see previous comment.

**Comment by Vylest** [comment]
Removed the duplicate data flows. Everything else looks good.
