### ISSUE TITLE
Grammar Review - DFD Dictionary

### ISSUE THREAD

**Issue by amarangonihengling** [APlusTeam/ISQA-3420#7]
Please, review the description of entities, process, and data stores of DFD Dictionary.

**Comment by gasrcpro** [comment]
Updated the grammar in the DFD Dictionary.

**Comment by amarangonihengling** [comment]
I think this issue should remain open while the DFD is incomplete. Every update on the DFD should trigger a review on the dictionary.

**Comment by amarangonihengling** [comment]
Closing the issue. Every time that someone updates the DFD, this person should create a new review issue and assign someone or himself.
