### ISSUE TITLE
DFD Diagram - Update

### ISSUE THREAD

**Issue by amarangonihengling** [APlusTeam/ISQA-3420#8]
Please, change the DFD diagram to be compliant to the presented in class.

**Comment by amarangonihengling** [comment]
Version 1.1

![dfd_1 1](https://cloud.githubusercontent.com/assets/11740062/10207439/e1044400-6791-11e5-96bd-016717d358f2.png)

**Comment by amarangonihengling** [comment]
![dfd](https://cloud.githubusercontent.com/assets/11740062/10263908/8eb23480-69c3-11e5-8357-a1c95dadcf91.jpg)

**Comment by Vylest** [comment]
Ok the new diagram looks great. Can I get the file?

**Comment by gasrcpro** [comment]
This has been completed, as noted in your comment with the updated DFD image.
